module.exports={
    Company:require('./CompanySchemes.js'),
    Support:require('./SupportSchemes.js'),
    Log:require('./LogSchemas.js'),
    Replacement:{
        ...require('./QuoteSchemes.js'),
        ...require('./JobSchemas.js'),
        ...require('./ProjectSchemes.js')
    }
}